### ISSUE TITLE
Bug: born in future

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/campy#2]
It is currently possible to be displayed as born in the future.
That should not be possible.
It should be checked if the person is older than nine or so.

**Comment by minthemiddle** [comment]
Args, feature tests needed. Worked flawlessly locally. Does not work live. Classic.

**Comment by minthemiddle** [comment]
Fixed via https://github.com/CodeDesignInitiative/campy/pull/12

**Comment by minthemiddle** [comment]
Not the nicest error message but working :)

![screen shot 2018-06-01 at 18 07 48](https://user-images.githubusercontent.com/1950766/40851183-d891c366-65c6-11e8-96fb-2f75aa8a89cb.png)
