### ISSUE TITLE
Add: PGP key for security disclosure email

### ISSUE THREAD

**Issue by fronbasal** [CodeDesignInitiative/campy#21]
There should be an PGP key for the security disclosure email.

**Comment by minthemiddle** [comment]
Could be solved in combination with #20 (Mailbox.org powered mail service)
Extra bonus: Not too closely linked with me, so when I'm not available, someone else can easily take over.

**Comment by minthemiddle** [comment]
Fixed via https://github.com/CodeDesignInitiative/campy/pull/24

**Comment by fronbasal** [comment]
Awesome. Thanks :)
