### ISSUE TITLE
Fix: Sqlite for testing

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/campy#57]
- Functional tests are written in Laravel Dusk which uses a headless Chrome browser to test things
- To run these tests on a CI server, we have to use SQLite
- Unfortunately, the CampUser table had a missing primary key
- Adding a primary key later to SQLite is not possible and results in errors

```
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1 Cannot add a PRIMARY KEY column
```

**Comment by Jubeki** [comment]
You could rename the table to whatever you want with
`ALTER TABLE orig_table_name RENAME TO tmp_table_name`
Then create a new table with the right columns.
After that copy the data to the new table.
So you can simply add a primary key

**Comment by minthemiddle** [comment]
Thanks for the suggestion. We are actually looking for a way that does comply with Laravel's migrations. The idea here is that you track all database changes in version control. 

Here's what the documentation says about why migrations should be used:

> Migrations are like version control for your database, allowing your team to easily modify and share the application's database schema. Migrations are typically paired with Laravel's schema builder to easily build your application's database schema. If you have ever had to tell a teammate to manually add a column to their local database schema, you've faced the problem that database migrations solve.
Source: https://laravel.com/docs/5.6/migrations

The original migration is here: https://github.com/CodeDesignInitiative/campy/blob/master/database/migrations/2018_05_14_150232_create_camp_user_table.php
The ID fix is here: https://github.com/CodeDesignInitiative/campy/blob/master/database/migrations/2018_06_09_132657_add_id_to_camp_users.php

**Comment by minthemiddle** [comment]
- This will not fix
- We use `enum` columns which are not supported by SQLite
- `dbal` does not support `enum` either, so we cannot migrate these columns to `string`
- Solution: Use MariaDB for the testing db as well
