### ISSUE TITLE
Privacy and gender

### ISSUE THREAD

**Issue by Jubeki** [CodeDesignInitiative/campy#67]
The privacy policy says that the gender will not be saved. For what purpose is then the column gender in the table users?

**Comment by minthemiddle** [comment]
We do not ask users about their gender.
But for statistical reasons, we will derive gender from the firstname.
That is why there is this column.
I probably have to update the privacy statement.

**Comment by minthemiddle** [comment]
Two possibilities:

1. Change the statement to "Wir speichern Information zum Geschlecht nur als statistische Wahrscheinlichkeitsableitung per Gender-API.com vom Vornamen ab" and leave column
2. Drop column on user and add column on camp (gender ratio). The query will then be: "Here is a list of all campgoers for camp x. Please tell me the probable gender."

I'm not totally sure how sensitive people are about their gender.
And hence, which option we should choose.
I will ask the community.
