### ISSUE TITLE
Enhancement: remove .DS_Store files and add to .gitignore

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/campy#73]
> There is currently only one at [./resources/lang/.DS_Store](blob), which is totally unnecessary.

##### Solve
- [ ] Add: */DS_Store to gitignore
- [ ] Cut: DS_Store files

<br></br>
---

### How to check for .DS_Store files or others
There are two different methods I have used:

1. Using the Github Website and just click <kbd>find file</kbd>, then you can type .DS_Store and every file should be listed
2. Using the shell (find & grep)
- You can easily find files including its relative path by just doing the following:
```bash
cd <repo-folder>
find . | grep .DS_Store
# now you got all the files with that name in this folder
```

[blob]: https://github.com/CodeDesignInitiative/campy/blob/master/resources/lang/.DS_Store

**Comment by minthemiddle** [comment]
Solved via #75 and #76
