### ISSUE TITLE
Fix: Date picker not working on Safari/FF Win

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/campy#82]
On registration, the datepicker for birthdate does not work for some browsers:
- Safari everywhere
- Firefox Windows

This is because some browser vendor have not implemented HTML5 datepicker properly yet.
This bug prevents people from registering.

**Comment by toorusr** [comment]
Not only FIrefox WIndows. 
Also on some Firefox linux.

**Comment by minthemiddle** [comment]
Does work right now, will be improved by #83
